CREATE TABLE payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_payment_methods_display_order CHECK (display_order >= 0),
    CONSTRAINT uq_payment_methods_name UNIQUE (name)
);

CREATE INDEX idx_payment_methods_display_order ON payment_methods (display_order, id);

INSERT INTO
    payment_methods (name, display_order)
VALUES
    ('現金', 10),
    ('カード', 20),
    ('PayPay', 30),
    ('その他', 40);

ALTER TABLE transactions
ADD COLUMN payment_method_id BIGINT;

UPDATE transactions
SET
    payment_method_id = (
        SELECT
            id
        FROM
            payment_methods
        WHERE
            name = '現金'
    );

ALTER TABLE transactions
ALTER COLUMN payment_method_id
SET NOT NULL;

ALTER TABLE transactions
ADD CONSTRAINT fk_transactions_payment_method FOREIGN KEY (payment_method_id) REFERENCES payment_methods (id) ON DELETE RESTRICT;

CREATE INDEX idx_transactions_payment_method_id ON transactions (payment_method_id);
