CREATE TABLE monthly_budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_year INTEGER NOT NULL,
    budget_month INTEGER NOT NULL,
    overall_budget INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_monthly_budgets_year CHECK (budget_year BETWEEN 1 AND 9999),
    CONSTRAINT ck_monthly_budgets_month CHECK (budget_month BETWEEN 1 AND 12),
    CONSTRAINT ck_monthly_budgets_overall_budget CHECK (
        overall_budget IS NULL
        OR overall_budget > 0
    ),
    CONSTRAINT uq_monthly_budgets_year_month UNIQUE (budget_year, budget_month)
);

CREATE TABLE category_budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monthly_budget_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    amount INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_category_budgets_monthly_budget FOREIGN KEY (monthly_budget_id) REFERENCES monthly_budgets (id) ON DELETE CASCADE,
    CONSTRAINT fk_category_budgets_category FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE,
    CONSTRAINT ck_category_budgets_amount CHECK (amount > 0),
    CONSTRAINT uq_category_budgets_month_category UNIQUE (monthly_budget_id, category_id)
);

CREATE INDEX idx_category_budgets_category_id ON category_budgets (category_id);
