CREATE TABLE recurring_transaction_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    day_of_month INTEGER NOT NULL,
    type VARCHAR(20) NOT NULL,
    category_id BIGINT,
    payment_method_id BIGINT,
    transfer_source_id BIGINT,
    transfer_destination_id BIGINT,
    default_amount INTEGER,
    memo VARCHAR(500),
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recurring_templates_category FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT,
    CONSTRAINT fk_recurring_templates_payment_method FOREIGN KEY (payment_method_id) REFERENCES payment_methods (id) ON DELETE RESTRICT,
    CONSTRAINT fk_recurring_templates_transfer_source FOREIGN KEY (transfer_source_id) REFERENCES transfer_accounts (id) ON DELETE RESTRICT,
    CONSTRAINT fk_recurring_templates_transfer_destination FOREIGN KEY (transfer_destination_id) REFERENCES transfer_accounts (id) ON DELETE RESTRICT,
    CONSTRAINT ck_recurring_templates_day_of_month CHECK (day_of_month BETWEEN 1 AND 31),
    CONSTRAINT ck_recurring_templates_type CHECK (type IN ('EXPENSE', 'INCOME', 'TRANSFER')),
    CONSTRAINT ck_recurring_templates_default_amount CHECK (
        default_amount IS NULL
        OR default_amount > 0
    ),
    CONSTRAINT ck_recurring_templates_display_order CHECK (display_order >= 0),
    CONSTRAINT ck_recurring_templates_targets_by_type CHECK (
        (
            type = 'EXPENSE'
            AND category_id IS NOT NULL
            AND payment_method_id IS NOT NULL
            AND transfer_source_id IS NULL
            AND transfer_destination_id IS NULL
        )
        OR (
            type = 'INCOME'
            AND category_id IS NOT NULL
            AND payment_method_id IS NULL
            AND transfer_source_id IS NULL
            AND transfer_destination_id IS NULL
        )
        OR (
            type = 'TRANSFER'
            AND category_id IS NULL
            AND payment_method_id IS NULL
            AND transfer_source_id IS NOT NULL
            AND transfer_destination_id IS NOT NULL
        )
    )
);

CREATE INDEX idx_recurring_templates_order ON recurring_transaction_templates (enabled, display_order, id);

CREATE INDEX idx_recurring_templates_category_id ON recurring_transaction_templates (category_id);

CREATE INDEX idx_recurring_templates_payment_method_id ON recurring_transaction_templates (payment_method_id);

CREATE INDEX idx_recurring_templates_transfer_source_id ON recurring_transaction_templates (transfer_source_id);

CREATE INDEX idx_recurring_templates_transfer_destination_id ON recurring_transaction_templates (transfer_destination_id);

CREATE TABLE recurring_transaction_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL,
    target_year INTEGER NOT NULL,
    target_month INTEGER NOT NULL,
    transaction_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recurring_registrations_template FOREIGN KEY (template_id) REFERENCES recurring_transaction_templates (id) ON DELETE CASCADE,
    CONSTRAINT fk_recurring_registrations_transaction FOREIGN KEY (transaction_id) REFERENCES transactions (id) ON DELETE CASCADE,
    CONSTRAINT ck_recurring_registrations_year CHECK (target_year BETWEEN 1 AND 9999),
    CONSTRAINT ck_recurring_registrations_month CHECK (target_month BETWEEN 1 AND 12),
    CONSTRAINT uq_recurring_registrations_template_month UNIQUE (template_id, target_year, target_month),
    CONSTRAINT uq_recurring_registrations_transaction UNIQUE (transaction_id)
);

CREATE INDEX idx_recurring_registrations_target_month ON recurring_transaction_registrations (target_year, target_month);
