CREATE TABLE mfa_recovery_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_user_id BIGINT NOT NULL,
    code_hash VARCHAR(100) NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mfa_recovery_codes_app_user FOREIGN KEY (app_user_id) REFERENCES app_user (id) ON DELETE CASCADE
);

CREATE INDEX idx_mfa_recovery_codes_app_user_id ON mfa_recovery_codes (app_user_id, used_at);
